---
runcmd:
  # Modify postfix's PRIMARY_DOMAIN in pca-gophish-composition docker-compose
  # file to the email-sending domain for this assessment
  - [sed, -i,
     "s|^\\([- \\w]*\\)PRIMARY_DOMAIN=[^\\w]*$|\
     \\1PRIMARY_DOMAIN=${email_sending_domain}|g",
     "${pca_docker_compose_file}"]
