---
# Write Thunderbird file that enables autoconfiguration of email accounts
# from the email-sending domain for this assessment.  For details, see:
# https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration
write_files:
  - path: "/usr/lib/thunderbird/isp/${email_sending_domain}.xml"
    permissions: "0644"
    owner: root:root
    content: |
      <?xml version="1.0"?>
      <clientConfig version="1.1">
        <emailProvider id="${email_sending_domain}">
          <domain>${email_sending_domain}</domain>
          <displayName>${email_sending_domain}</displayName>
          <displayShortName>${email_sending_domain}</displayShortName>
          <incomingServer type="imap">
            <hostname>${email_sending_domain}</hostname>
            <port>993</port>
            <socketType>SSL</socketType>
            <authentication>password-cleartext</authentication>
            <username>%EMAILLOCALPART%</username>
          </incomingServer>
          <outgoingServer type="smtp">
            <hostname>${email_sending_domain}</hostname>
            <port>587</port>
            <socketType>STARTTLS</socketType>
            <authentication>password-cleartext</authentication>
            <username>%EMAILLOCALPART%</username>
          </outgoingServer>
        </emailProvider>
      </clientConfig>
