---

# Create a mount point for the EFS
runcmd:
  - [mkdir, -p, "${mount_point}"]

# Add an fstab entry for the EFS mount
mounts:
  - ["${efs_id}:/", "${mount_point}", efs, "_netdev,iam,nofail,tls", "0", "0"]
